version: '3'
services:
  ml_api:
    build:
      context: ../
      dockerfile: k8s/milvus/Dockerfile
    container_name: ml_api_milvus
    depends_on:
      - cadvisor
    expose:
      - 5000
    ports:
      - "5000:5000"   # expose webserver to localhost host:container

  search_ui:
    container_name: search_ui
    build:
      context: ../
      dockerfile: search_ui/Dockerfile
    expose:
      - 80
    ports:
      - '80:80'

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./config/prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    expose:
      - 9090
    ports:
      - 9090:9090
    depends_on:
      - cadvisor

  grafana:
    image: grafana/grafana
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=foobar
      - GF_USERS_ALLOW_SIGN_UP=false

  cadvisor:
    image: google/cadvisor
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8080:8080

  db:
    image: redislabs/rejson
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    expose:
      - 6379
    volumes:
      - redis_data:/data

volumes:
  prometheus_data: {}
  grafana_data: {}
  redis_data: {}
