apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: semsearch-clip-milvus-redis
  name: semsearch-clip-milvus-redis
spec:
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: semsearch-clip-milvus-redis
  type: LoadBalancer
status:
  loadBalancer: {}
